// AUTO-GENERATED — edit data/*.txt files, then run scripts/generate_data_js.py
// Do not edit this file directly.

const ARTICLES = [
  {
    slug: "40_it_provoz",
    rubrika: "IT Provoz",
    datum: "10. 04. 2026",
    nazev: "Zavedení nového systému zálohování firemních dat",
    text: "IT oddělení dokončilo migraci firemní zálohovací infrastruktury na nový systém Veeam Backup & Replication v kombinaci s cloudovým úložištěm Microsoft Azure Blob Storage. Přechod proběhl úspěšně v průběhu března a dubna 2026 bez výpadků produkčního prostředí. Nový systém zajišťuje zálohu všech kritických serverů a databází každé čtyři hodiny, přičemž zálohy jsou automaticky replikovány do geograficky odděleného datového centra. Zálohy jsou šifrovány algoritmem AES-256, čímž je zajištěna plná ochrana dat v souladu s GDPR a interní bezpečnostní politikou. Klíčovým vylepšením je zkrácení doby obnovy dat (RTO) z původních 6 hodin na méně než 45 minut v případě havárie. Rovněž se zkrátil cílový bod obnovení (RPO) z 24 hodin na 4 hodiny. Systém umožňuje granulární obnovu jednotlivých souborů, e-mailů i databázových záznamů bez nutnosti obnovovat celý server. IT oddělení plánuje v červnu 2026 provést plný disaster recovery test za účasti klíčových IT správců a bezpečnostního týmu. Výsledky testu budou reportovány vedení IT a vedení společnosti.",
    url: "/#/article/40_it_provoz"
  },
  {
    slug: "39_vývoj",
    rubrika: "Vývoj",
    datum: "09. 04. 2026",
    nazev: "Zahájení výzkumného partnerství s VUT Brno v oblasti vodíkového pohonu",
    text: "Oddělení vývoje a inovací formalizovalo výzkumné partnerství s Vysokým učením technickým v Brně – konkrétně s Ústavem automobilního a dopravního inženýrství. Cílem spolupráce je výzkum aplikace vodíkového palivového článku jako zdroje pohonu pro lehká užitková vozidla. Tříleté partnerství je financováno z kombinace prostředků Auron Automotive (60 %) a grantu Technologické agentury ČR v rámci programu TREND (40 %). Celkový rozpočet projektu činí 28 milionů Kč. Výstupem projektu bude funkční demonstrátor vodíkového pohonného systému integrovaný do lehkého dodávkového vozidla platformy Auron. Na straně VUT se projektu účastní tým šesti výzkumných pracovníků a čtyř doktorandů. Auron Automotive přidělil projektu tříčlenný tým seniorních inženýrů z oddělení pohonných soustav a elektrotechniky. Konzultanty projektu jsou odborníci ze společnosti Hydrogen Valley CZ. Pravidelné technické revize projektu budou probíhat čtvrtletně. Výsledky výzkumu budou předmětem ochrany duševního vlastnictví sdíleně mezi Auron Automotive a VUT Brno. Vedoucím projektu na straně Auron je Ing. Tomáš Kovář, Ph.D.",
    url: "/#/article/39_vývoj"
  },
  {
    slug: "38_marketing",
    rubrika: "Marketing",
    datum: "08. 04. 2026",
    nazev: "Auron Automotive se stává partnerem české fotbalové ligy",
    text: "Společnost Auron Automotive uzavřela tříletou partnerskou smlouvu s Ligovou fotbalovou asociací (LFA), čímž se stává generálním partnerem české nejvyšší fotbalové soutěže. Partnerství vstoupí v platnost od sezóny 2026/2027. V rámci spolupráce bude logo Auron Automotive zobrazováno na dresech rozhodčích, na perimetrovém reklamním pásu ve všech klubových stadionech a na přímých přenosech z utkání. Součástí balíčku je také pojmenování ocenění nejlepšího hráče kola – „Hráč kola Auron Automotive\". Pro zaměstnance přináší partnerství exkluzivní výhody: každý zaměstnanec obdrží vstupenky na tři zápasy České ligy v průběhu sezóny; celkový počet vstupenek bude distribuován losem prostřednictvím HR portálu. Součástí balíčku jsou i VIP vstupenky na finále MOL Cupu. Partnerství s českou likou posílí povědomí o značce Auron v domácím trhu a navazuje na strategii marketingového oddělení cílit na sportovně aktivní zákazníky ve věkové skupině 30–55 let. Tisková konference k partnerství proběhne 14. dubna 2026.",
    url: "/#/article/38_marketing"
  },
  {
    slug: "37_správa_majetku",
    rubrika: "Správa majetku",
    datum: "07. 04. 2026",
    nazev: "Instalace solárních panelů na střechy výrobních hal zahájena",
    text: "V souladu s programem dekarbonizace výroby byla zahájena instalace fotovoltaických panelů na střechy hal 1 a 3. Instalaci provádí společnost SolarTech CZ, která byla vybrána ve výběrovém řízení na základě nejnižší ceny a prokázaných referencí. Celková instalovaná kapacita fotovoltaické elektrárny na obou halách dosáhne 1,6 MWp. Roční výroba elektřiny se odhaduje na 1 500 MWh, což pokryje přibližně 22 % spotřeby výrobního závodu. Přebytky vyrobené elektrické energie budou prodávány do distribuční sítě. Z bezpečnostních důvodů bude po dobu instalace (předpokládaný termín 7. dubna – 31. května 2026) omezen pohyb osob na střechách a v jejich bezprostřední blízkosti. Vstupy do označených zón jsou povoleny výhradně pracovníkům instalační firmy a oprávněným osobám správy majetku. Po dokončení instalace proběhne ceremoniál spuštění elektrárny za účasti vedení společnosti. Monitoring výroby elektřiny bude dostupný v reálném čase na nástěnce v hale 1 a na intranetu.",
    url: "/#/article/37_správa_majetku"
  },
  {
    slug: "36_personální_informace",
    rubrika: "Personální informace",
    datum: "06. 04. 2026",
    nazev: "Nový zaměstnanecký benefit: příspěvek na elektrokolo nebo e-scooter",
    text: "Společnost Auron Automotive rozšiřuje od 1. května 2026 nabídku zaměstnaneckých benefitů o příspěvek na pořízení elektrokola nebo elektrického koloběžky (e-scooter). Příspěvek ve výši až 15 000 Kč je jednorázový a hrazený z fondu FKSP. Benefit je určen pro zaměstnance s minimálně dvouletým pracovním poměrem na plný úvazek. Podmínkou čerpání je využití elektrokola/e-scooteru k dojíždění do zaměstnání alespoň 50 dní v kalendářním roce, což zaměstnanec stvrdí čestným prohlášením. Žádost o příspěvek se podává prostřednictvím HR portálu; součástí je doložení dokladu o koupi. Příspěvek je osvobozen od daně z příjmu do zákonného limitu. V případě ukončení pracovního poměru do 12 měsíců od čerpání je zaměstnanec povinen vrátit poměrnou část příspěvku. Nový benefit zapadá do širší strategie společnosti podporovat udržitelné dojíždění do práce a snižovat emise CO₂ spojené s dopravou zaměstnanců. Bližší informace najdete v sekci Benefity na HR portálu nebo u svého HR business partnera.",
    url: "/#/article/36_personální_informace"
  },
  {
    slug: "35_it",
    rubrika: "IT",
    datum: "05. 04. 2026",
    nazev: "Povinné zavedení dvoufaktorového ověřování pro všechny zaměstnance",
    text: "IT oddělení oznamuje, že od 1. května 2026 bude pro přístup do všech firemních systémů povinné dvoufaktorové ověřování (MFA – Multi-Factor Authentication). Tato změna navazuje na doporučení bezpečnostního auditu provedeného v lednu 2026. Zaměstnanci si budou moci zvolit jednu ze dvou metod ověření: aplikaci Microsoft Authenticator v mobilním telefonu nebo hardwarový bezpečnostní klíč FIDO2. Aplikace Authenticator je k dispozici zdarma v App Store i Google Play. IT oddělení zajistí hardwarové klíče pro zaměstnance bez kompatibilního mobilního zařízení. Aktivace MFA probíhá přes portál myaccount.microsoft.com při přihlášení firemním účtem. Postup krok za krokem je k dispozici v IT sekci intranetu. Pro zaměstnance bez přístupu k počítači připraví IT oddělení kiosky s asistovanou aktivací ve vestibulech budov A, B a C. Zavedení MFA výrazně zvýší odolnost firemních dat proti phishingu a krádeži přihlašovacích údajů. IT helpdesk je k dispozici na lince 200 nebo na helpdesk@auron-automotive.cz pro všechny dotazy k aktivaci.",
    url: "/#/article/35_it"
  },
  {
    slug: "34_investice",
    rubrika: "Investice",
    datum: "04. 04. 2026",
    nazev: "Schválení výstavby nového testovacího polygonu",
    text: "Představenstvo společnosti Auron Automotive na svém zasedání dne 2. dubna 2026 schválilo investici ve výši 180 milionů Kč do výstavby vlastního testovacího polygonu. Areál bude situován v těsné blízkosti stávajícího výrobního závodu na přilehlém pozemku o rozloze 42 hektarů. Polygon bude obsahovat okruh s délkou 3,2 km, simulátor různých typů vozovek (beton, dlažba, mokrý asfalt, hrbolatý povrch), brzdný úsek a dynamické testovací plochy. Součástí areálu bude také klimatizovaná zkušebna pro testy v kontrolovaných teplotních podmínkách. Výstavba umožní internalizovat testovací kapacity, které dosud musely být zajišťovány externě v zahraničí. Odhadovaná úspora nákladů na testování dosahuje 25 milionů Kč ročně. Polygon bude rovněž k dispozici pro pronájem třetím stranám v automobilovém průmyslu. Zahájení stavby je naplánováno na říjen 2026, dokončení na červen 2028. Projekt povede oddělení investic ve spolupráci s projektovou kanceláří a externím generálním projektantem.",
    url: "/#/article/34_investice"
  },
  {
    slug: "33_nákup",
    rubrika: "Nákup",
    datum: "03. 04. 2026",
    nazev: "Aktualizace podmínek výběrových řízení platná od 2. čtvrtletí 2026",
    text: "Oddělení nákupu vydává aktualizovanou verzi Podmínek pro výběrová řízení (PVŘ 2026), která vstupuje v platnost od 1. dubna 2026. Změny reagují na nové legislativní požadavky v oblasti udržitelného nákupu a ESG reportingu. Nově jsou všichni dodavatelé s ročním obratem nad 5 milionů Kč povinni doložit platný certifikát ISO 14001 nebo ekvivalentní prohlášení o environmentální politice. Dodavatelé bez certifikátu mají možnost předložit akční plán k jeho získání s termínem do konce roku 2026. Součástí aktualizace je i zavedení etického kodexu pro dodavatele a povinné přijetí Kodexu chování společnosti Auron Automotive (Supplier Code of Conduct). Podpis tohoto dokumentu bude podmínkou pro uzavření nebo prodloužení smlouvy. Kompletní dokumentace PVŘ 2026 je ke stažení na nákupním portálu SRM. Dotazy k novým podmínkám zodpoví kategoriální manažeři nákupu nebo právní oddělení.",
    url: "/#/article/33_nákup"
  },
  {
    slug: "32_výroba",
    rubrika: "Výroba",
    datum: "02. 04. 2026",
    nazev: "Zavedení systému prediktivní údržby na klíčových výrobních linkách",
    text: "Oddělení výroby ve spolupráci s IT oddělením spouští pilotní provoz systému prediktivní údržby (Predictive Maintenance) na výrobních linkách v halách 2 a 4. Systém využívá síť IoT senzorů k průběžnému sledování vibrací, teplot a odběru proudu u klíčových strojů. Data ze senzorů jsou vyhodnocována pomocí algoritmů strojového učení, které dokáží s předstihem tří až sedmi dnů identifikovat hrozící poruchu. Cílem je snížení neplánovaných prostojů o 40 % a optimalizace intervalu preventivní údržby. Systém byl vyvinut ve spolupráci se společností Siemens Digital Industries a v pilotní fázi pokrývá 28 kritických strojů. Výsledky pilotu budou vyhodnoceny po šesti měsících provozu a v případě úspěchu bude systém rozšířen do všech výrobních hal. Servisní technici a operátoři absolvovali úvodní školení k práci s novým rozhraním. Výstrahy systému jsou integrovány do stávajícího dispečerského systému a zasílány také formou notifikací do mobilní aplikace vedoucích směn.",
    url: "/#/article/32_výroba"
  },
  {
    slug: "31_marketing",
    rubrika: "Marketing",
    datum: "01. 04. 2026",
    nazev: "Nový firemní web Auron Automotive spuštěn",
    text: "Dne 1. dubna 2026 byl spuštěn zcela přepracovaný firemní web na adrese www.auron-automotive.cz. Nový web je výsledkem osmiměsíčního projektu realizovaného ve spolupráci s digitální agenturou Pixelcraft Praha. Web byl navržen s důrazem na mobilní uživatele a rychlé načítání – Lighthouse skóre výkonu dosahuje hodnoty 94/100. Navigace je přehledně rozdělena do sekcí Modely, Dealer síť, Kariéra a Pro media. Konfigurátor vozidel byl kompletně přepracován a nově umožňuje 3D zobrazení vozu v reálném čase s výběrem barev a výbavy. Součástí webu je nová sekce Udržitelnost, kde jsou zveřejňovány informace o environmentálních cílech společnosti, výroční zprávy a výsledky ESG hodnocení. Sekce pro média nabízí přímý přístup k tiskovým zprávám, fotografiím a videomateriálům ve vysokém rozlišení. Zpětnou vazbu k webu lze zasílat prostřednictvím formuláře v patičce stránky. Marketingové oddělení uvítá podněty od zaměstnanců i z pohledu zákazníků.",
    url: "/#/article/31_marketing"
  },
  {
    slug: "30_vývoj",
    rubrika: "Vývoj",
    datum: "31. 03. 2026",
    nazev: "Aerodynamické zkoušky nového modelu Auron GT Sport v tunelu FKFS Stuttgart",
    text: "Vývojový tým dokončil sérii aerodynamických zkoušek prototypu modelu Auron GT Sport v prestižním aerodynamickém tunelu institutu FKFS ve Stuttgartu. Testování probíhalo v týdnu od 23. do 28. března 2026. Cílem zkoušek bylo ověření koeficientu odporu vzduchu (Cd) a optimalizace tlakového rozložení na přední i zadní nápravě při rychlostech 80, 120 a 200 km/h. Dosažená hodnota Cd 0,27 je o 12 % nižší než u předchozí generace modelu GT. Na základě výsledků byly provedeny úpravy tvaru předního splitteru a zadního difuzoru. Tyto úpravy přinesou zlepšení spotřeby paliva o přibližně 4 % při dálniční jízdě a zároveň zlepší stabilitu vozu při vysokých rychlostech. Kompletní výsledková zpráva bude interně k dispozici od 10. dubna. Vývojový tým připraví prezentaci pro vedení divize v rámci technického review plánovaného na 17. dubna 2026.",
    url: "/#/article/30_vývoj"
  },
  {
    slug: "29_it_provoz",
    rubrika: "IT Provoz",
    datum: "30. 03. 2026",
    nazev: "Plánovaná odstávka serverové infrastruktury – 5. dubna 2026",
    text: "IT oddělení oznamuje plánovanou údržbovou odstávku klíčové serverové infrastruktury v neděli 5. dubna 2026 v době od 2:00 do 8:00 hodin. Během tohoto okna budou nedostupné systémy SAP, firemní e-mail, sdílené disky a intranetový portál. Důvodem odstávky je instalace bezpečnostních záplat operačního systému, upgrade firmwaru síťových prvků a přepnutí záložního napájení serverovny na nový UPS systém. Práce budou prováděny v koordinaci s dodavateli HP a Cisco. Zaměstnanci pracující v nočních směnách jsou informováni prostřednictvím svých vedoucích. Pro urgentní případy bude k dispozici pohotovostní IT linka +420 555 100 200. Výrobní MES systém bude během odstávky provozován v offline režimu s omezenou funkcionalitou. Obnova všech systémů je plánována nejpozději v 8:00. V případě prodloužení odstávky budou uživatelé informováni prostřednictvím SMS notifikace. IT oddělení se omlouvá za způsobené komplikace.",
    url: "/#/article/29_it_provoz"
  },
  {
    slug: "28_správa_majetku",
    rubrika: "Správa majetku",
    datum: "29. 03. 2026",
    nazev: "Zahájení rekonstrukce firemní kantýny",
    text: "Od 6. dubna 2026 bude zahájena plánovaná rekonstrukce hlavní firemní kantýny v budově C. Rekonstrukce potrvá přibližně osm týdnů a zahrnuje výměnu technologického vybavení kuchyně, modernizaci výdejního pultu a obnovu interiéru jídelny. Po dobu rekonstrukce bude stravování zajištěno v náhradním výdejním místě v budově D (vestibul, přízemí). Provozní doba náhradního výdeje: 10:30–13:30. Jídelní lístek zůstane zachován v plném rozsahu včetně výběru ze tří jídel a vegetariánské varianty. Zaměstnancům pracujícím na noční směně bude zajištěn teplý pokrm formou termoportů přímo na pracovišti ve výrobní hale. Podrobnosti sdělí příslušní vedoucí směn. Rekonstruovaná kantýna bude vybavena moderní technologií pro výdej jídel pomocí QR kódu a bezkontaktní platby. Kapacita jídelny se rozšíří z 280 na 360 míst. Dokončení a slavnostní otevření je plánováno na červen 2026.",
    url: "/#/article/28_správa_majetku"
  },
  {
    slug: "27_personální_informace",
    rubrika: "Personální informace",
    datum: "28. 03. 2026",
    nazev: "Otevření přihlášek na letní rekreační pobyty 2026",
    text: "Personální oddělení oznamuje zahájení přihlašování na letní rekreační pobyty pro zaměstnance a jejich rodinné příslušníky. Pro rok 2026 společnost Auron Automotive nabízí pobyty v celkem sedmi rekreačních střediscích v tuzemsku i v zahraničí. Novinkou tohoto roku je zařazení dvou zahraničních destinací – Chorvatského pobřeží (Vodice) a slovenských Vysokých Tater. Cena pobytů je pro zaměstnance dotována z fondu FKSP ve výši 40–60 % v závislosti na pracovním zařazení a délce pracovního poměru. Přihlašování probíhá výhradně prostřednictvím HR portálu v sekci „Benefity – rekreace\" od 1. dubna do 30. dubna 2026. Přihlášky jsou přijímány v pořadí, v jakém jsou doručeny; kapacita jednotlivých středisek je omezena. Bližší informace o každém středisku, včetně fotografií a termínů, jsou dostupné na intranetu v sekci Personalistika. V případě dotazů se obraťte na HR business partnery nebo navštivte oddělení personalistiky v budově A, kanceláři 214.",
    url: "/#/article/27_personální_informace"
  },
  {
    slug: "26_nákup",
    rubrika: "Nákup",
    datum: "27. 03. 2026",
    nazev: "Výběrové řízení na dodavatele karosářských dílů pro model Auron X4",
    text: "Oddělení nákupu vyhlašuje výběrové řízení na dodavatele lisovaných karosářských dílů pro nový model Auron X4. Výběrové řízení se týká celkem 34 dílů včetně bočních prahů, střešních příček a výztuh nárazníků. Zájemci o účast v tendru musí splňovat certifikační požadavky IATF 16949 a prokázat zkušenost s dodávkami do automobilového průmyslu v objemu minimálně 50 000 ks ročně. Preferováni jsou dodavatelé z Česka, Slovenska nebo Polska z důvodu minimalizace logistických rizik. Registrace do tendru probíhá prostřednictvím nákupního portálu SRM do 15. dubna 2026. Technická dokumentace a výkresová dokumentace budou zpřístupněny po podpisu NDA. Hodnotícím kritériem bude cena (60 %), kvalita (25 %) a logistická spolehlivost (15 %). Výsledky výběrového řízení budou oznámeny do konce května 2026. Dotazy k výběrovému řízení zasílejte na adresu nakup.tender@auron-automotive.cz.",
    url: "/#/article/26_nákup"
  },
  {
    slug: "25_it",
    rubrika: "IT",
    datum: "26. 03. 2026",
    nazev: "Spuštění cloudového datového skladu pro analytické účely",
    text: "IT oddělení ve spolupráci s oddělením controllingu spouští nový cloudový datový sklad postavený na platformě Microsoft Azure Synapse Analytics. Cílem projektu je sjednotit datové zdroje z různých systémů a umožnit pokročilou analytiku a reportování v reálném čase. Do datového skladu budou integrovány klíčové systémy: SAP S/4HANA, MES výrobního závodu, CRM systém a systém pro správu kvality. Migrace dat proběhne ve dvou vlnách – první v dubnu, druhá v červnu 2026. Novinkou pro uživatele je přístup k interaktivním dashboardům přes Power BI. Vedoucí pracovníci budou mít k dispozici přehledy o výrobě, prodeji a kvalitě bez nutnosti čekat na pravidelné měsíční reporty. Školení pro klíčové uživatele jsou naplánována na druhý týden v dubnu. Přihlášení je možné přes interní vzdělávací portál. IT oddělení zároveň připravuje průvodce a FAQ dokumentaci dostupnou na intranetu.",
    url: "/#/article/25_it"
  },
  {
    slug: "24_investice",
    rubrika: "Investice",
    datum: "25. 03. 2026",
    nazev: "Auron Automotive spouští program dekarbonizace výroby",
    text: "Vedení společnosti Auron Automotive schválilo strategický investiční program zaměřený na snížení uhlíkové stopy výrobního závodu o 45 % do roku 2030. Program s celkovým objemem investic 320 milionů Kč bude realizován ve třech fázích. V první fázi (2026–2027) bude provedena instalace fotovoltaické elektrárny o výkonu 2,4 MWp na střechách hal 1, 3 a 5, doplněná o bateriové úložiště. Tím dojde ke snížení odběru elektrické energie ze sítě o přibližně 35 %. Druhá fáze zahrnuje přechod technologických procesů z plynového vytápění na tepelná čerpadla a modernizaci kompresorové stanice. Ve třetí fázi bude realizována elektrifikace interní logistiky – náhrada naftových vysokozdvižných vozíků za elektrické. Program byl podpořen dotačním titulem z Modernizačního fondu EU. Realizace je v gesci oddělení investic ve spolupráci s externím poradenským týmem EkoFlex Advisory.",
    url: "/#/article/24_investice"
  },
  {
    slug: "23_výroba",
    rubrika: "Výroba",
    datum: "24. 03. 2026",
    nazev: "Spuštění nové robotické svářecí linky v hale 5",
    text: "Dne 21. 3. 2026 byla úspěšně spuštěna nová robotická svářecí linka v hale 5. Instalace zahrnuje šest svářecích robotů značky KUKA, přičemž celková investice do linky přesáhla 45 milionů Kč. Nová linka umožňuje svařování hliníkových i ocelových karosářských dílů s přesností na desetiny milimetru. Oproti původní lince dochází ke zvýšení kapacity o 30 % a současně ke snížení zmetkovitosti o odhadovaných 18 %. Obsluhu linky zajišťují proškolení operátoři, kteří absolvovali čtyřtýdenní certifikační kurz ve spolupráci s dodavatelem technologie. Systém je plně integrován se stávajícím MES systémem a umožňuje sledování kvality v reálném čase. Vedoucí výroby Martin Blaha ocenil nasazení celého technického týmu při záběhu linky. V nejbližších týdnech bude probíhat dolaďování parametrů a postupné navyšování taktovacího cyklu na plný výrobní objem.",
    url: "/#/article/23_výroba"
  },
  {
    slug: "22_vývoj",
    rubrika: "Vývoj",
    datum: "23. 03. 2026",
    nazev: "Testování prototypu elektromobilu Auron E3 vstupuje do druhé fáze",
    text: "Oddělení vývoje oznamuje zahájení druhé fáze testování prototypu plně elektrického vozidla Auron E3. Po úspěšném absolvování laboratorních zkoušek bude vůz podroben rozsáhlému testování na veřejných komunikacích v různých klimatických podmínkách. Klíčovým cílem této fáze je ověření výdrže a výkonu bateriového systému o kapacitě 82 kWh při extrémních teplotách. Testy probíhají ve spolupráci s certifikačním centrem v Mostě a externím laboratořím v Norsku, kde budou simulovány podmínky arktické zimy. Prototyp disponuje dojezdem přes 520 km dle cyklu WLTP a systémem rychlonabíjení s výkonem 150 kW. Předpokládaná sériová výroba modelu Auron E3 je naplánována na druhý kvartál roku 2028. Výsledky testů budou průběžně sdíleny s vedením divize i s investory. Vývojový tým oceňuje spolupráci interních útvarů – zejména oddělení elektroniky a výroby – při přípravě testovacích vozidel.",
    url: "/#/article/22_vývoj"
  },
  {
    slug: "21_marketing",
    rubrika: "Marketing",
    datum: "22. 03. 2026",
    nazev: "Účast na Autosalonu Praha 2026",
    text: "Společnost Auron Automotive se zúčastní Autosalonu Praha 2026, který se koná od 15. do 24. května v Pražském výstavišti. Výstava přiláká tisíce návštěvníků z celé střední Evropy a představuje pro nás klíčovou příležitost k prezentaci nové modelové řady. Na vlastním stánku o rozloze 600 m² budeme vystavovat tři klíčové modely: nový crossover Auron X4, elektrický sedan Auron E3 a limitovanou edici Auron GT Sport. Hlavním lákadlem bude světová premiéra modelu Auron X4 ve verzi plug-in hybrid. Marketingové oddělení ve spolupráci s agenturou Design Republic připravilo interaktivní expozici s možností virtuálního testování vozidel a konfigurátorem v reálném čase. Součástí programu jsou každodenní tiskové konference a odborné panelové diskuze. Zaměstnanci, kteří mají zájem o návštěvu výstavy v rámci firemního dne, se mohou přihlásit prostřednictvím HR portálu do 10. dubna 2026. Vstupenky a dopravu zajišťuje firma.",
    url: "/#/article/21_marketing"
  },
  {
    slug: "20_it_provoz",
    rubrika: "IT Provoz",
    datum: "21. 03. 2026",
    nazev: "Bezpečnostní incident – phishingový útok na firemní e-mailové účty",
    text: "IT oddělení a bezpečnostní tým oznamují, že v týdnu od 16. do 18. března 2026 byl zaznamenán cílený phishingový útok na e-mailové účty zaměstnanců společnosti Auron Automotive. Útok byl identifikován a neutralizován; zatím nejsou potvrzeny žádné úniky citlivých dat. Útočníci rozesílali e-maily napodobující komunikaci od IT oddělení s výzvou k aktualizaci přihlašovacích údajů přes falešnou přihlašovací stránku. Celkem bylo odesláno přibližně 340 podvodných e-mailů; kliknutí na odkaz bylo zaznamenáno u 12 zaměstnanců. U čtyř z nich došlo k zadání přihlašovacích údajů – jejich hesla byla okamžitě resetována a účty zabezpečeny. Všichni zaměstnanci jsou žádáni, aby zvýšili ostražitost a v případě pochybností o pravosti e-mailu neklikali na žádné odkazy a nespouštěli přílohy. IT oddělení nikdy nevyžaduje zadání hesla přes e-mail ani přes webový formulář. Podezřelé e-maily nahlaste okamžitě na phishing@auron-automotive.cz. V reakci na incident IT oddělení urychluje zavedení povinného MFA a spouští v dubnu 2026 povinné online školení kybernetické bezpečnosti pro všechny zaměstnance. Splnění školení bude evidováno a bude součástí hodnocení zaměstnanců za rok 2026.",
    url: "/#/article/20_it_provoz"
  },
  {
    slug: "19_nákup",
    rubrika: "Nákup",
    datum: "20. 03. 2026",
    nazev: "Zavedení nového nákupního portálu SRM 2.0",
    text: "Oddělení nákupu spouští k 1. dubnu 2026 novou verzi nákupního portálu SRM 2.0, postavenou na platformě SAP Ariba. Nový portál nahrazuje stávající systém, který byl v provozu od roku 2019 a přestal odpovídat rostoucím požadavkům na funkčnost a integraci s SAP S/4HANA. Klíčové novinky SRM 2.0 zahrnují automatizované schvalování objednávek do 50 000 Kč, integraci s katalogy preferovaných dodavatelů, elektronické podepisování smluv a dashboard pro sledování stavu objednávek v reálném čase. Pro dodavatele přináší portál přehledné rozhraní pro správu nabídek, fakturaci a komunikaci s nákupním týmem. Přechod na SRM 2.0 proběhne skokově – od 1. dubna budou veškeré nové objednávky zadávány výhradně v novém systému. Stávající otevřené objednávky v SRM 1.0 budou migrovány automaticky. Školení pro interní uživatele proběhnou v týdnech 23.–27. 3. a 30. 3.–3. 4. 2026. Registrace dodavatelů do nového portálu je otevřena od 15. března 2026. Instrukce pro dodavatele jsou dostupné na webové stránce nakup.auron-automotive.cz/srm2. Technická podpora pro přechod je zajišťována nákupním oddělením na e-mailu srm-podpora@auron-automotive.cz.",
    url: "/#/article/19_nákup"
  },
  {
    slug: "18_investice",
    rubrika: "Investice",
    datum: "19. 03. 2026",
    nazev: "Auron Automotive uzavírá investici do startupu vyvíjejícího software pro autonomní řízení",
    text: "Společnost Auron Automotive uzavřela strategickou investici ve výši 4,2 milionu eur do pražského technologického startupu AutoPilot.AI, který vyvíjí softwarovou platformu pro pokročilé asistenční systémy jízdy (ADAS) a autonomní řízení úrovně 3. Investice má formu menšinového podílu ve výši 18 % a zahrnuje i opci na navýšení podílu v průběhu příštích tří let. Strategickým záměrem je získat přednostní přístup k technologiím AutoPilot.AI a integrovat je do připravovaných modelů Auron E3 a nástupce modelu GT Sport. AutoPilot.AI zaměstnává 43 inženýrů specializujících se na počítačové vidění, strojové učení a embeddované systémy. Startup má za sebou úspěšnou spolupráci s dvěma evropskými výrobci vozidel a disponuje vlastní zkušební flotilou čítající šest testovacích vozidel. Investice byla schválena představenstvem společnosti v únoru 2026. Součástí dohody je i vzájemná výměna technických pracovníků a sdílení testovací infrastruktury. Koordinaci spolupráce na straně Auron zajistí divize vývoje a inovací.",
    url: "/#/article/18_investice"
  },
  {
    slug: "17_správa_majetku",
    rubrika: "Správa majetku",
    datum: "18. 03. 2026",
    nazev: "Rozšíření systému přístupu na karty – nové turnikety v hale 1 a 2",
    text: "Oddělení správy majetku dokončilo instalaci nového systému řízení přístupu v halách 1 a 2. Původní magnetické turnikety byly nahrazeny modernějšími zařízeními s kombinovanou technologií RFID a biometrie (sken dlaně). Nový systém zajišťuje vyšší bezpečnost díky eliminaci rizika kopírování karet. Přístup do hal je nově podmíněn ověřením zaměstnanecké karty v kombinaci se skenem žil dlaně, čímž se prakticky vylučuje neoprávněný vstup. Data biometrického skeneru jsou uložena lokálně v zařízení a nejsou přenášena do centrálního systému. Zaměstnanci hal 1 a 2 jsou povinni zaregistrovat svůj biometrický identifikátor na enrolmentním kiosku umístěném u vstupu do každé haly. Registrace trvá přibližně dvě minuty a probíhá do 31. března 2026. Po tomto datu bude bez biometrické registrace přístup do chráněných zón zamezen. Zaměstnanci, kteří mají zdravotní důvody bránící biometrickému snímání, jsou žádáni, aby kontaktovali oddělení správy majetku nebo HR pro nastavení alternativního způsobu ověření.",
    url: "/#/article/17_správa_majetku"
  },
  {
    slug: "16_personální_informace",
    rubrika: "Personální informace",
    datum: "17. 03. 2026",
    nazev: "Vyhlášení výsledků průzkumu spokojenosti zaměstnanců 2026",
    text: "Personální oddělení zveřejňuje výsledky výročního průzkumu spokojenosti zaměstnanců, který proběhl v únoru 2026. Průzkumu se zúčastnilo celkem 1 847 zaměstnanců, což představuje účast 73 % – nejvyšší hodnotu v historii společnosti. Celkový index spokojenosti dosáhl hodnoty 72 bodů ze 100, což je nárůst o 5 bodů oproti roku 2025. Nejlépe hodnocenou oblastí byla spolupráce v týmu (průměr 81) a jistota zaměstnání (79). Největší prostor pro zlepšení zaměstnanci vidí v oblasti interní komunikace (62) a kariérního rozvoje (64). Na základě výsledků průzkumu připraví HR oddělení ve spolupráci s vedením divizi akční plány zaměřené na zlepšení kriticky hodnocených oblastí. Výsledky budou prezentovány na setkání zaměstnanců s vedením plánovaném na 8. dubna 2026 v aule budovy A. Plné výsledky průzkumu – včetně srovnání po odděleních – jsou dostupné vedoucím pracovníkům v HR portálu. Anonymita odpovědí respondentů je garantována – výsledky jsou zobrazovány pouze pro skupiny s minimálně 10 respondenty.",
    url: "/#/article/16_personální_informace"
  },
  {
    slug: "15_výroba",
    rubrika: "Výroba",
    datum: "16. 03. 2026",
    nazev: "Zahájení sériové výroby nové generace přední nápravy pro model Auron X4",
    text: "Výrobní závod oznamuje zahájení sériové výroby nové generace přední nápravy McPherson pro model Auron X4. Výroba startuje v hale 2 od 16. března 2026 s taktovacím cyklem 78 sekund. Nová náprava je oproti předchozí generaci lehčí o 4,2 kg díky použití kovaných hliníkových ramen místo ocelových. Zároveň přináší zlepšenou kinematiku podvozku, která příznivě ovlivňuje chování vozu při zatáčení a tlumení nerovností vozovky. Změna konstrukčního materiálu si vyžádala úpravy technologického procesu v sekci obrábění a montáže. Operátoři prošli dvoutýdenním interním školením na nové pracovní postupy a obsluhu upraveného montážního přípravku. Technologický tým úspěšně provedl záběhovou sérii 500 kusů s výslednou zmetkovitostí pod 0,3 %. Plný výrobní objem 420 kusů denně bude dosažen do konce března. Vedoucí výroby Blaha ocenil spolupráci logistiky, kvality a technologie při přípravě náběhu nového dílu.",
    url: "/#/article/15_výroba"
  },
  {
    slug: "14_it",
    rubrika: "IT",
    datum: "15. 03. 2026",
    nazev: "Přechod firemní komunikace na Microsoft Teams – ukončení podpory Skype for Business",
    text: "IT oddělení oznamuje ukončení podpory platformy Skype for Business k 30. dubna 2026. Veškerá interní komunikace – instant messaging, telefonní hovory i videkonference – přejde výhradně na Microsoft Teams, který je v provozu od loňského roku. Zaměstnanci jsou žádáni, aby do konce března 2026 exportovali případné záznamy ze Skype for Business, které potřebují archivovat. Po 30. dubnu bude přístup k Skype for Business trvale zablokován. IT oddělení neprovede žádnou automatickou migraci historických konverzací. Školení pro pokročilé funkce Microsoft Teams – zejména práci s kanály, plánování schůzek a integraci s SharePointem – jsou nabízena každý čtvrtek od 13:00 online. Přihlášení přes vzdělávací portál v sekci IT školení. Pro jednotlivce nebo menší týmy lze domluvit individuální session přes helpdesk. Přechod plně na Teams je součástí širší strategie sjednocení komunikačních nástrojů a snížení licenčních nákladů. Dotazy k migraci adresujte na helpdesk@auron-automotive.cz nebo linku 200.",
    url: "/#/article/14_it"
  },
  {
    slug: "13_vývoj",
    rubrika: "Vývoj",
    datum: "14. 03. 2026",
    nazev: "Úspěšné ukončení nárazových testů modelu Auron X4 dle standardu Euro NCAP",
    text: "Oddělení vývoje oznamuje, že model Auron X4 úspěšně absolvoval sadu nárazových testů dle metodiky Euro NCAP 2026. Testy proběhly v akreditované zkušebně IDIADA v Barceloně v průběhu února a začátkem března 2026. Model Auron X4 dosáhl celkového hodnocení pět hvězdiček. V kategorii ochrany dospělých spolujezdců získal 88 %, v kategorii ochrany dětí 92 %, v kategorii ochrany chodců 82 % a v kategorii asistenčních systémů 79 %. Výsledky jsou srovnatelné s nejlepšími vozy v segmentu kompaktních crossoverů. Klíčem k úspěchu byl nově navržený systém přední deformační zóny a aktualizovaný software systému automatického nouzového brzdění AEB, který dokáže detekovat i cyklisty a motocyklisty v bočním pohybu. Tyto prvky vyvíjelo oddělení pasivní a aktivní bezpečnosti po dobu dvou let. Výsledky testů budou použity jako klíčový argument v marketingové komunikaci a na veletrhu v Praze. Podrobná zpráva Euro NCAP bude zveřejněna na webu organizace Euro NCAP v dubnu 2026.",
    url: "/#/article/13_vývoj"
  },
  {
    slug: "12_nákup",
    rubrika: "Nákup",
    datum: "13. 03. 2026",
    nazev: "Konsolidace portfolia dodavatelů elektronických komponent",
    text: "Oddělení nákupu zahajuje projekt konsolidace portfolia dodavatelů elektronických komponent. Cílem je snížit počet aktivních dodavatelů v kategorii elektronika z 38 na 22 do konce roku 2026, čímž dojde ke zlepšení smluvních podmínek a snížení administrativní zátěže. V rámci konsolidace budou osloveni stávající dodavatelé s nabídkou rozšíření spolupráce. Dodavatelé, kteří nesplní aktualizovaná kvalifikační kritéria – zejména v oblasti kybernetické bezpečnosti a ochrany dat – budou postupně vyřazeni. Termíny přechodu budou komunikovány individuálně prostřednictvím kategoriálních manažerů. Projekt se dotkne zejména oblasti řídicích jednotek, senzorů, kabelových svazků a nabíjecích komponent pro elektrifikované modely. Nákupní tým ve spolupráci s oddělením vývoje připravuje technické specifikace pro nová výběrová řízení plánovaná na druhý kvartál 2026. Informační schůzka pro dotčené kategoriální manažery se koná 20. března 2026 v zasedací místnosti B3. Podkladové materiály budou distribuovány e-mailem den před schůzkou.",
    url: "/#/article/12_nákup"
  },
  {
    slug: "11_marketing",
    rubrika: "Marketing",
    datum: "12. 03. 2026",
    nazev: "Zahájení spolupráce s lifestyle influencery pro propagaci modelu Auron E3",
    text: "Marketingové oddělení spouští novou influencer kampaň zaměřenou na propagaci připravovaného elektrického modelu Auron E3 na sociálních sítích Instagram a YouTube. Kampaň běží v období od dubna do července 2026 a cílí na věkovou skupinu 25–40 let. Do kampaně bylo vybráno celkem osm influencerů s celkovým dosahem přesahujícím 3,5 milionu sledujících. Obsahem spolupráce jsou testovací recenze, srovnání s konkurencí a behind-the-scenes videa z výrobního závodu. Vybraní tvůrci obsahu navštíví závod Auron Automotive osobně v dubnu 2026. Kampaň je koordinována externě agenturou Media Forward, která zajišťuje výběr influencerů, schvalování obsahu a sledování KPI. Marketingové oddělení stanovilo cíl dosáhnout 8 milionů organických zobrazení za dobu trvání kampaně. Zaměstnanci, kteří chtějí sdílet obsah kampaně na svých osobních profilech, mohou využít připravené materiály dostupné na intranetu v sekci Komunikace – Sdílení obsahu. Žádáme, aby veřejná vyjádření zaměstnanců byla v souladu s firemní komunikační politikou.",
    url: "/#/article/11_marketing"
  },
  {
    slug: "10_it_provoz",
    rubrika: "IT Provoz",
    datum: "11. 03. 2026",
    nazev: "Dočasná nedostupnost systému evidence smluv",
    text: "Z důvodu technických problémů může docházet k dočasné nedostupnosti systému evidence smluv. IT oddělení pracuje na odstranění problému.",
    url: "/#/article/10_it_provoz"
  },
  {
    slug: "09_nákup",
    rubrika: "Nákup",
    datum: "10. 03. 2026",
    nazev: "Nová administrativní budova pro oddělení nákupu",
    text: "Oddělení nákupu se v průběhu léta 2026 přesune do nové administrativní budovy. Cílem je soustředit nákupní týmy na jedno místo a zlepšit spolupráci.",
    url: "/#/article/09_nákup"
  },
  {
    slug: "08_investice",
    rubrika: "Investice",
    datum: "09. 03. 2026",
    nazev: "Výstavba nové lakovny byla zahájena",
    text: "Společnost Auron Automotive zahájila výstavbu nové lakovny, která umožní zvýšení kapacity a snížení ekologické zátěže. Dokončení projektu je plánováno na konec roku 2027.",
    url: "/#/article/08_investice"
  },
  {
    slug: "07_správa_majetku",
    rubrika: "Správa majetku",
    datum: "08. 03. 2026",
    nazev: "Otevření nových parkovacích garáží",
    text: "Od 15. 3. 2026 budou zaměstnancům k dispozici nové parkovací garáže v blízkosti administrativní budovy B. Garáže jsou určeny především pro zaměstnance směnného provozu.",
    url: "/#/article/07_správa_majetku"
  },
  {
    slug: "06_personální_informace",
    rubrika: "Personální informace",
    datum: "07. 03. 2026",
    nazev: "MUDr. Petr Novák nebude přítomen v ordinaci",
    text: "Dne 12. 3. 2026 nebude závodní lékař MUDr. Petr Novák přítomen v ordinaci z důvodu odborného školení. Akutní případy budou řešeny ve spolupráci s externím poskytovatelem.",
    url: "/#/article/06_personální_informace"
  },
  {
    slug: "05_výroba",
    rubrika: "Výroba",
    datum: "06. 03. 2026",
    nazev: "Porucha balicího stroje v hale 3",
    text: "Dne 5. 3. 2026 došlo k poruše balicího stroje v hale 3. Oprava je v řešení ve spolupráci s externím dodavatelem. Výroba není v tuto chvíli ohrožena.",
    url: "/#/article/05_výroba"
  },
  {
    slug: "04_it",
    rubrika: "IT",
    datum: "05. 03. 2026",
    nazev: "Nasazení nového SAP systému",
    text: "V průběhu dubna 2026 bude zahájeno postupné nasazení nového ERP systému SAP S/4HANA. Migrace se dotkne finančních, logistických a nákupních procesů.",
    url: "/#/article/04_it"
  },
  {
    slug: "03_vývoj",
    rubrika: "Vývoj",
    datum: "04. 03. 2026",
    nazev: "Zahájení vývoje nové generace převodovek",
    text: "Oddělení vývoje zahájilo práce na nové generaci automatických převodovek, které budou určeny pro elektrifikované modely. Projekt je plánován na období 2026–2028.",
    url: "/#/article/03_vývoj"
  },
  {
    slug: "02_nákup",
    rubrika: "Nákup",
    datum: "03. 03. 2026",
    nazev: "Změna schvalovacího procesu objednávek",
    text: "Od 1. března 2026 dochází ke změně schvalovacího procesu nákupních objednávek nad 250 000 Kč. Nový proces má za cíl zvýšit transparentnost a zrychlit schvalování.",
    url: "/#/article/02_nákup"
  },
  {
    slug: "01_marketing",
    rubrika: "Marketing",
    datum: "02. 03. 2026",
    nazev: "Spuštění interní kampaně k novému modelu",
    text: "Marketingové oddělení zahajuje interní kampaň zaměřenou na představení nového modelu vozidla Auron X4. Cílem kampaně je sjednotit komunikaci napříč odděleními a připravit zaměstnance na externí marketingové aktivity.",
    url: "/#/article/01_marketing"
  }
];
