"""
Generates frontend/data.js from data/*.txt files.
Single source of truth: edit data/*.txt, then run this script.

Usage:
    python scripts/generate_data_js.py
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).parent.parent
DATA_DIR = ROOT / "data"
OUTPUT = ROOT / "frontend" / "data.js"


def parse_txt(path: Path) -> dict:
    content = path.read_text(encoding="utf-8")
    lines = content.splitlines()

    meta = {}
    body_lines = []
    in_body = False

    for line in lines:
        if in_body:
            body_lines.append(line)
        elif line.startswith("Rubrika:"):
            meta["rubrika"] = line.split(":", 1)[1].strip()
        elif line.startswith("Datum:"):
            meta["datum"] = line.split(":", 1)[1].strip()
        elif line.startswith("Slug:"):
            meta["slug"] = line.split(":", 1)[1].strip()
        elif line.startswith("Název:"):
            meta["nazev"] = line.split(":", 1)[1].strip()
        elif line.strip() == "" and "nazev" in meta:
            in_body = True

    meta["text"] = " ".join(" ".join(body_lines).split())  # normalize whitespace
    meta["url"] = f"/#/article/{meta.get('slug', path.stem)}"
    meta.setdefault("slug", path.stem)
    meta.setdefault("rubrika", "")
    meta.setdefault("datum", "")
    meta.setdefault("nazev", path.stem)
    return meta


def datum_sort_key(article: dict) -> tuple:
    """Parse 'DD. MM. YYYY' for sorting newest-first."""
    m = re.match(r"(\d+)\.\s*(\d+)\.\s*(\d+)", article.get("datum", ""))
    if m:
        return (int(m.group(3)), int(m.group(2)), int(m.group(1)))
    return (0, 0, 0)


def main():
    txt_files = sorted(DATA_DIR.glob("*.txt"))
    if not txt_files:
        print(f"No .txt files found in {DATA_DIR}")
        return

    articles = [parse_txt(f) for f in txt_files]
    articles.sort(key=datum_sort_key, reverse=True)

    lines = [
        "// AUTO-GENERATED — edit data/*.txt files, then run scripts/generate_data_js.py",
        "// Do not edit this file directly.",
        "",
        "const ARTICLES = [",
    ]
    for i, a in enumerate(articles):
        comma = "," if i < len(articles) - 1 else ""
        lines.append("  {")

        def js(v):
            return json.dumps(v, ensure_ascii=False)

        lines.append(f"    slug: {js(a['slug'])},")
        lines.append(f"    rubrika: {js(a['rubrika'])},")
        lines.append(f"    datum: {js(a['datum'])},")
        lines.append(f"    nazev: {js(a['nazev'])},")
        lines.append(f"    text: {js(a['text'])},")
        lines.append(f"    url: {js(a['url'])}")
        lines.append(f"  }}{comma}")

    lines.append("];")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written {len(articles)} articles to {OUTPUT}")


if __name__ == "__main__":
    main()
